import Foundation

public enum DocumentType: String, Codable, Sendable {
    case passport
    case visa
    case ticket
    case hotelBooking
    case healthInsurance
    case unknown
}

public enum DocumentFormat: String, Codable, Sendable {
    case pdf
    case jpg
    case png
    case text
    case markdown
    case gpx
    case webp
    case heic
    case bmp
    case gif
    case video
    case audio
    case dicom
    case unknown

    /// Formats offered on import. Video / audio / DICOM stay for older stored files only.
    public static let importable: Set<DocumentFormat> = [
        .pdf, .jpg, .png, .text, .markdown, .gpx, .webp, .heic, .bmp, .gif,
    ]
}

public enum MetadataField: String, Codable, Sendable {
    case idNumber
    case holderName
    case expiryDate
    case issueDate
    case bookingReference
    case flightDetails
    case hotelName
    case policyNumber
    case coveragePeriod
    case destination
    case visaNumber
}

public struct Tag: Equatable, Codable, Sendable {
    public var name: String
    public var isAutoGenerated: Bool

    public init(name: String, isAutoGenerated: Bool) {
        self.name = name
        self.isAutoGenerated = isAutoGenerated
    }
}

public struct Document: Equatable, Codable, Sendable {
    public var id: String
    public var memberId: String
    public var type: DocumentType
    public var format: DocumentFormat
    public var originalFileName: String?
    public var metadata: [MetadataField: String]
    public var tags: [Tag]
    public var createdAt: Date
    public var updatedAt: Date
    public var extractionConfidence: Float?
    public var requiresManualReview: Bool
    public var ocrText: String

    public init(
        id: String,
        memberId: String,
        type: DocumentType,
        format: DocumentFormat,
        originalFileName: String?,
        metadata: [MetadataField: String],
        tags: [Tag],
        createdAt: Date,
        updatedAt: Date,
        extractionConfidence: Float?,
        requiresManualReview: Bool,
        ocrText: String = ""
    ) {
        self.id = id
        self.memberId = memberId
        self.type = type
        self.format = format
        self.originalFileName = originalFileName
        self.metadata = metadata
        self.tags = tags
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.extractionConfidence = extractionConfidence
        self.requiresManualReview = requiresManualReview
        self.ocrText = ocrText
    }
}

public struct SafetyPlace: Equatable, Codable, Sendable {
    public var latitude: Double
    public var longitude: Double
    public var timestamp: Int64
    public var batteryPercent: Int

    public init(latitude: Double, longitude: Double, timestamp: Int64, batteryPercent: Int = -1) {
        self.latitude = latitude
        self.longitude = longitude
        self.timestamp = timestamp
        self.batteryPercent = batteryPercent
    }
}

public enum Product {
    public static let name = "Paperstow"
    public static let intendedBundleID = "com.app.paperstow"
}
