import Foundation
import PaperstowCore
import XCTest

final class LimitsAndSearchTests: XCTestCase {
    func testCapsMatchAndroid() {
        XCTAssertEqual(Limits.maxDocumentsPerMember, 100)
        XCTAssertEqual(Limits.maxTagsPerDocument, 20)
        XCTAssertEqual(Limits.maxFolderImportFiles, 500)
        XCTAssertTrue(Limits.canAddDocument(currentCount: 99))
        XCTAssertFalse(Limits.canAddDocument(currentCount: 100))
        XCTAssertEqual(Limits.folderImportCap(Array(0..<600)).count, 500)
    }

    func testAutoTags() {
        XCTAssertEqual(
            AutoTags.generate(type: .passport, metadata: [
                .destination: "Japan",
                .expiryDate: "2030-05-01",
                .issueDate: "2020-01-01",
            ]),
            ["passport", "japan", "expires-2030", "issued-2020"]
        )
        XCTAssertEqual(AutoTags.generate(type: .unknown, metadata: [:]), [])
    }

    func testSearchMatch() {
        let doc = Document(
            id: "1",
            memberId: "default",
            type: .passport,
            format: .pdf,
            originalFileName: "john_doe_passport.pdf",
            metadata: [.holderName: "John Doe"],
            tags: [Tag(name: "passport", isAutoGenerated: true)],
            createdAt: Date(),
            updatedAt: Date(),
            extractionConfidence: 0.9,
            requiresManualReview: false,
            ocrText: "PASSPORT United States"
        )
        XCTAssertTrue(SearchMatch.matches(doc, query: "john"))
        XCTAssertTrue(SearchMatch.matches(doc, query: "UNITED"))
        XCTAssertTrue(SearchMatch.matches(doc, query: "passport"))
        XCTAssertFalse(SearchMatch.matches(doc, query: "visa"))
        XCTAssertEqual(Product.intendedBundleID, "com.app.paperstow")
    }
}
