name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  swift-test:
    name: PaperstowCore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Test
        run: swift test --package-path .
